### PR TITLE
Add check whether contract's name ends with 'Contract'

### LINKED ISSUE #58: Check whether contract's name ends with "Contract"
To avoid structs such as "TestContractContract" if the name field in the ABI is "TestContract"

### PR DESCRIPTION
**Pull request by andreireanu**
Fixes #58

### CODE REVIEW

**Comment by gfusee** [comment]
I don't like the idea to "block" the user if he has a contract's name which ends with "Contract", this is really common

Adding a logic to not append "Contract" if it's already present would provide a smoother developer experience

"Adder" => "AdderContract"
"AdderContract" => "AdderContract"

**Comment by andreireanu** [comment]
Got it, I redid the commit

**Review by gfusee — APPROVED** [review]

**Comment by gfusee** [comment]
Merged, thanks @andreireanu for your work! 🔥

**Comment by andreireanu** [comment]
Glad to help!

**Pull request merged**
